import type { AgentDef, PersonaSeed } from "soul-core";

const kael: PersonaSeed = {
  version: 1,
  id: "warrior-001",
  name: "Kael",
  bigFive: [0.3, 0.8, 0.6, 0.4, 0.7],
  coreValues: ["loyalty", "justice", "survival"],
  selfConcept: "I am a protector of the weak",
  roles: ["warrior", "guardian"],
  temperament: { valence: -0.1, arousal: 0.5 },
  wounds: [
    {
      label: "betrayal",
      trigger: "betrayal or backstabbing",
      sensitivity: 0.8,
      emotionalResponse: "anger",
    },
  ],
};

const lyra: PersonaSeed = {
  version: 1,
  id: "scholar-001",
  name: "Lyra",
  bigFive: [0.9, 0.6, 0.3, 0.7, 0.3],
  coreValues: ["curiosity", "compassion", "freedom"],
  selfConcept: "I seek truth above all",
  roles: ["scholar", "healer"],
  temperament: { valence: 0.2, arousal: 0.3 },
};

const vex: PersonaSeed = {
  version: 1,
  id: "rogue-001",
  name: "Vex",
  bigFive: [0.5, 0.3, 0.7, 0.2, 0.8],
  coreValues: ["freedom", "survival", "cunning"],
  selfConcept: "Trust no one but yourself",
  roles: ["rogue", "thief"],
  temperament: { valence: -0.2, arousal: 0.6 },
  wounds: [
    {
      label: "abandonment",
      trigger: "being left behind or abandoned",
      sensitivity: 0.7,
      emotionalResponse: "fear",
    },
  ],
};

const elena: PersonaSeed = {
  version: 1,
  id: "healer-001",
  name: "Elena",
  bigFive: [0.6, 0.7, 0.8, 0.9, 0.2],
  coreValues: ["compassion", "benevolence", "tradition"],
  selfConcept: "I heal the wounded and guide the lost",
  roles: ["healer", "priestess"],
  temperament: { valence: 0.3, arousal: 0.2 },
};

const bjorn: PersonaSeed = {
  version: 1,
  id: "blacksmith-001",
  name: "Bjorn",
  bigFive: [0.2, 0.9, 0.5, 0.3, 0.4],
  coreValues: ["craftsmanship", "loyalty", "security"],
  selfConcept: "My craft defines me",
  roles: ["blacksmith", "craftsman"],
  temperament: { valence: 0.0, arousal: 0.4 },
};

const mira: PersonaSeed = {
  version: 1,
  id: "merchant-001",
  name: "Mira",
  bigFive: [0.5, 0.5, 0.9, 0.6, 0.5],
  coreValues: ["prosperity", "community", "fairness"],
  selfConcept: "I bring prosperity to the village",
  roles: ["merchant", "trader"],
  temperament: { valence: 0.2, arousal: 0.4 },
};

const theron: PersonaSeed = {
  version: 1,
  id: "sage-001",
  name: "Theron",
  bigFive: [0.95, 0.5, 0.4, 0.8, 0.1],
  coreValues: ["wisdom", "truth", "tradition"],
  selfConcept: "Knowledge is the true power",
  roles: ["sage", "advisor"],
  temperament: { valence: 0.1, arousal: 0.1 },
  relationships: [
    { targetId: "scholar-001", tags: ["mentor"], trust: 0.9, affection: 0.8 },
  ],
};

const finn: PersonaSeed = {
  version: 1,
  id: "apprentice-001",
  name: "Finn",
  bigFive: [0.7, 0.4, 0.8, 0.3, 0.7],
  coreValues: ["curiosity", "adventure", "recognition"],
  selfConcept: "I will prove myself worthy",
  roles: ["apprentice", "adventurer"],
  temperament: { valence: 0.1, arousal: 0.6 },
  relationships: [
    {
      targetId: "blacksmith-001",
      tags: ["mentor"],
      trust: 0.7,
      affection: 0.6,
    },
  ],
};

export const AGENT_DEFS: AgentDef[] = [
  {
    seed: kael,
    nameKo: "카엘",
    color: "#e74c3c",
    emoji: "⚔️",
    homeLocationId: "house_kael",
    workLocationId: "barracks",
    schedule: [
      {
        startHour: 5,
        endHour: 7,
        locationId: "house_kael",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 7,
        endHour: 9,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 9,
        endHour: 12,
        locationId: "barracks",
        activity: "training",
        activityKo: "훈련",
      },
      {
        startHour: 12,
        endHour: 13,
        locationId: "tavern",
        activity: "lunch",
        activityKo: "점심 식사",
      },
      {
        startHour: 13,
        endHour: 18,
        locationId: "gate_north",
        activity: "patrol",
        activityKo: "순찰",
      },
      {
        startHour: 18,
        endHour: 20,
        locationId: "tavern",
        activity: "dinner",
        activityKo: "저녁 식사",
      },
      {
        startHour: 20,
        endHour: 22,
        locationId: "plaza",
        activity: "relax",
        activityKo: "휴식",
      },
    ],
  },
  {
    seed: lyra,
    nameKo: "리라",
    color: "#9b59b6",
    emoji: "📖",
    homeLocationId: "house_lyra",
    workLocationId: "library",
    schedule: [
      {
        startHour: 5,
        endHour: 7,
        locationId: "house_lyra",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 7,
        endHour: 8,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 8,
        endHour: 12,
        locationId: "library",
        activity: "research",
        activityKo: "연구",
      },
      {
        startHour: 12,
        endHour: 13,
        locationId: "plaza",
        activity: "lunch walk",
        activityKo: "점심 산책",
      },
      {
        startHour: 13,
        endHour: 17,
        locationId: "library",
        activity: "study",
        activityKo: "공부",
      },
      {
        startHour: 17,
        endHour: 19,
        locationId: "church",
        activity: "meditation",
        activityKo: "명상",
      },
      {
        startHour: 19,
        endHour: 21,
        locationId: "tavern",
        activity: "dinner",
        activityKo: "저녁 식사",
      },
      {
        startHour: 21,
        endHour: 22,
        locationId: "house_lyra",
        activity: "journaling",
        activityKo: "일지 작성",
      },
    ],
  },
  {
    seed: vex,
    nameKo: "벡스",
    color: "#2ecc71",
    emoji: "🗡️",
    homeLocationId: "house_vex",
    workLocationId: "market",
    schedule: [
      {
        startHour: 7,
        endHour: 9,
        locationId: "house_vex",
        activity: "late wake",
        activityKo: "늦잠",
      },
      {
        startHour: 9,
        endHour: 10,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 10,
        endHour: 14,
        locationId: "market",
        activity: "scouting",
        activityKo: "정찰",
      },
      {
        startHour: 14,
        endHour: 16,
        locationId: "plaza",
        activity: "socializing",
        activityKo: "사교 활동",
      },
      {
        startHour: 16,
        endHour: 18,
        locationId: "gate_south",
        activity: "wandering",
        activityKo: "방랑",
      },
      {
        startHour: 18,
        endHour: 21,
        locationId: "tavern",
        activity: "gambling",
        activityKo: "도박",
      },
      {
        startHour: 21,
        endHour: 22,
        locationId: "house_vex",
        activity: "planning",
        activityKo: "계획 수립",
      },
    ],
  },
  {
    seed: elena,
    nameKo: "엘레나",
    color: "#f1c40f",
    emoji: "✨",
    homeLocationId: "house_elena",
    workLocationId: "church",
    schedule: [
      {
        startHour: 5,
        endHour: 6,
        locationId: "house_elena",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 6,
        endHour: 8,
        locationId: "church",
        activity: "morning prayer",
        activityKo: "아침 기도",
      },
      {
        startHour: 8,
        endHour: 9,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 9,
        endHour: 12,
        locationId: "church",
        activity: "healing",
        activityKo: "치유",
      },
      {
        startHour: 12,
        endHour: 13,
        locationId: "plaza",
        activity: "walk",
        activityKo: "산책",
      },
      {
        startHour: 13,
        endHour: 16,
        locationId: "church",
        activity: "service",
        activityKo: "예배",
      },
      {
        startHour: 16,
        endHour: 18,
        locationId: "market",
        activity: "gathering herbs",
        activityKo: "약초 채집",
      },
      {
        startHour: 18,
        endHour: 20,
        locationId: "tavern",
        activity: "dinner",
        activityKo: "저녁 식사",
      },
      {
        startHour: 20,
        endHour: 22,
        locationId: "house_elena",
        activity: "rest",
        activityKo: "휴식",
      },
    ],
  },
  {
    seed: bjorn,
    nameKo: "비요른",
    color: "#e67e22",
    emoji: "🔨",
    homeLocationId: "house_bjorn",
    workLocationId: "blacksmith",
    schedule: [
      {
        startHour: 5,
        endHour: 6,
        locationId: "house_bjorn",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 6,
        endHour: 7,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 7,
        endHour: 12,
        locationId: "blacksmith",
        activity: "forging",
        activityKo: "단조",
      },
      {
        startHour: 12,
        endHour: 13,
        locationId: "tavern",
        activity: "lunch",
        activityKo: "점심 식사",
      },
      {
        startHour: 13,
        endHour: 18,
        locationId: "blacksmith",
        activity: "work",
        activityKo: "작업",
      },
      {
        startHour: 18,
        endHour: 20,
        locationId: "tavern",
        activity: "dinner and socializing",
        activityKo: "저녁 식사 및 사교",
      },
      {
        startHour: 20,
        endHour: 22,
        locationId: "house_bjorn",
        activity: "rest",
        activityKo: "휴식",
      },
    ],
  },
  {
    seed: mira,
    nameKo: "미라",
    color: "#1abc9c",
    emoji: "💰",
    homeLocationId: "house_mira",
    workLocationId: "market",
    schedule: [
      {
        startHour: 5,
        endHour: 7,
        locationId: "house_mira",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 7,
        endHour: 8,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 8,
        endHour: 13,
        locationId: "market",
        activity: "selling",
        activityKo: "판매",
      },
      {
        startHour: 13,
        endHour: 14,
        locationId: "tavern",
        activity: "lunch",
        activityKo: "점심 식사",
      },
      {
        startHour: 14,
        endHour: 18,
        locationId: "market",
        activity: "trading",
        activityKo: "거래",
      },
      {
        startHour: 18,
        endHour: 20,
        locationId: "tavern",
        activity: "dinner",
        activityKo: "저녁 식사",
      },
      {
        startHour: 20,
        endHour: 22,
        locationId: "house_mira",
        activity: "rest",
        activityKo: "휴식",
      },
    ],
  },
  {
    seed: theron,
    nameKo: "테론",
    color: "#3498db",
    emoji: "🔮",
    homeLocationId: "house_lyra",
    workLocationId: "library",
    schedule: [
      {
        startHour: 6,
        endHour: 8,
        locationId: "house_lyra",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 8,
        endHour: 9,
        locationId: "plaza",
        activity: "morning walk",
        activityKo: "아침 산책",
      },
      {
        startHour: 9,
        endHour: 12,
        locationId: "library",
        activity: "research",
        activityKo: "연구",
      },
      {
        startHour: 12,
        endHour: 14,
        locationId: "tavern",
        activity: "lunch and stories",
        activityKo: "점심 및 이야기",
      },
      {
        startHour: 14,
        endHour: 17,
        locationId: "library",
        activity: "teaching",
        activityKo: "가르침",
      },
      {
        startHour: 17,
        endHour: 19,
        locationId: "church",
        activity: "contemplation",
        activityKo: "명상",
      },
      {
        startHour: 19,
        endHour: 21,
        locationId: "tavern",
        activity: "evening tales",
        activityKo: "저녁 이야기",
      },
    ],
  },
  {
    seed: finn,
    nameKo: "핀",
    color: "#fd79a8",
    emoji: "🔥",
    homeLocationId: "house_bjorn",
    workLocationId: "blacksmith",
    schedule: [
      {
        startHour: 5,
        endHour: 7,
        locationId: "house_bjorn",
        activity: "wake up",
        activityKo: "기상",
      },
      {
        startHour: 7,
        endHour: 8,
        locationId: "tavern",
        activity: "breakfast",
        activityKo: "아침 식사",
      },
      {
        startHour: 8,
        endHour: 12,
        locationId: "blacksmith",
        activity: "apprentice work",
        activityKo: "견습 작업",
      },
      {
        startHour: 12,
        endHour: 14,
        locationId: "plaza",
        activity: "lunch and exploring",
        activityKo: "점심 및 탐험",
      },
      {
        startHour: 14,
        endHour: 16,
        locationId: "blacksmith",
        activity: "work",
        activityKo: "작업",
      },
      {
        startHour: 16,
        endHour: 18,
        locationId: "gate_north",
        activity: "adventure dreaming",
        activityKo: "모험 꿈꾸기",
      },
      {
        startHour: 18,
        endHour: 20,
        locationId: "tavern",
        activity: "dinner",
        activityKo: "저녁 식사",
      },
      {
        startHour: 20,
        endHour: 22,
        locationId: "barracks",
        activity: "sneaky training",
        activityKo: "몰래 훈련",
      },
    ],
  },
];
